# Generated by Django 4.0.10 on 2023-10-12 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SentEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(max_length=254)),
                ('recipients', models.CharField(max_length=1000)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('attachments', models.FileField(blank=True, null=True, upload_to='email_attachments/')),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('scheduled_send_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='EmailMessage',
        ),
    ]
