# Generated by Django 4.0.10 on 2023-10-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0002_sentemail_delete_emailmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='attachments'),
        ),
    ]
