# Generated by Django 4.0.10 on 2023-10-12 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0003_alter_sentemail_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sentemail',
            name='attachments',
            field=models.FileField(blank=True, null=True, upload_to='email_attachments/'),
        ),
    ]
