# Generated by Django 4.0.10 on 2023-10-12 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0004_alter_sentemail_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='sentemail',
            name='status',
            field=models.CharField(choices=[('QUEUED', 'queued'), ('SENT', 'sent'), ('REJECTED', 'rejected'), ('FAILED', 'failed'), ('BOUNCED', 'bounced'), ('DEFERRED', 'deferred'), ('DELIVERED', 'delivered'), ('AUTORESPONDED', 'autoresponded'), ('OPENED', 'opened'), ('CLICKED', 'clicked'), ('COMPLAINED', 'complained'), ('UNSUBSCRIBED', 'unsubscribed'), ('SUBSCRIBED', 'subscribed'), ('UNKNOWN', 'unknown')], default='QUEUED', max_length=13),
        ),
    ]
