# Generated by Django 4.0.10 on 2023-10-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailSender', '0006_alter_sentemail_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sentemail',
            old_name='attachments',
            new_name='attachment',
        ),
        migrations.RemoveField(
            model_name='sentemail',
            name='recipients',
        ),
        migrations.AddField(
            model_name='sentemail',
            name='recipient',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
